services:
  pixelplein:
    build: .
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
      # uncomment to override defaults:
      # - DISPLAY_WIDTH=1920
      # - DISPLAY_HEIGHT=1080
      # - THUMB_W=960
      # - THUMB_H=540
    labels:
      - traefik.enable=true
      - traefik.http.routers.pixelplein.rule=Host(`rsw.logicbit.nl`)
      - traefik.http.routers.pixelplein.entrypoints=websecure
      - traefik.http.routers.pixelplein.tls.certresolver=le
      - traefik.http.services.pixelplein.loadbalancer.server.port=3000
    volumes:
      - ./config.json:/app/config.json
      - photos:/app/photos
      - data:/app/data
      - cache:/app/cache
      - slide-assets:/app/slide-assets
      - submission-assets:/app/submission-assets
    networks:
      - web

networks:
  web:
    external: true

volumes:
  photos:
  data:
  cache:
  slide-assets:
  submission-assets:
